### ISSUE TITLE
Allocator shouldn't use drop to free itself

### ISSUE THREAD

**Issue by SimonBorghese** [gwihlidal/vk-mem-rs#69]
The `Allocator` struct using Rust dropping rather than manually freeing can have issues if it's dropped after the Vulkan instance, device, etc.. is dropped.
For example, say a program stored all of the Vulkan objects in a struct
```rust
struct VulkanThing{
  device: ash::Device
  allocator: vk_mem::Allocator
  ...
}
```

And the struct used a method to cleanup the program rather than using a drop

```rust
impl VulkanThing{
  pub fn cleanup(&mut self){
    self.device.destroy_device(...);
    ...
  }
}
```

This would result in an error as in this scenario below:
```rust
VulkanThing::init() // An allocator is created and put into struct
VulkanThing::cleanup() // Vulkan is unloaded

// Allocator is dropped here and an ERROR is raised
```

The error I get is `User-mode data execution prevention (DEP) violation at 0x...`

Instead of dropping, the option to manually free the allocator should be added such that the programmer can free the allocator in their cleanup method when the time is right.

**Comment by SimonBorghese** [comment]
It's also worth mentioning that a Vulkan Validation Layer will report unfree'd DeviceMemory if the Allocator is dropped after the device,

**Comment by MarijnS95** [comment]
A user normally does this by wrapping their `Allocator` in `ManuallyDrop`.

**Comment by SimonBorghese** [comment]
Correct me if I'm wrong but that isn't documented anywhere right?
Perhaps users should be notified in the readme of this behavior?

**Comment by MarijnS95** [comment]
If this library is well written it should have an `unsafe` constructor stating that `vk::Device` must not be destroyed before the `Allocator` to guarantee safe behaviour.

**Comment by Neo-Zhixing** [comment]
Like @MarijnS95 pointed out, the best way to resolve this issue is
1. In your `VulkanThing`, define the allocator to be before the device.
```rs
struct VulkanThing{
  device: ash::Device
  allocator: vk_mem::Allocator
  ...
}
```
2. Or even better, use `ManuallyDrop`.

It's inappropriate for `vk-mem-rs` to take ownership of the device because well, it's just the wrong place to own the device.

`vk-mem-rs` largely has the same level of memory safety guarantees as `ash`, so it's really the users responsibility to ensure that things are dropped in the correct order.

However, @MarijnS95  did have a point. I've marked the `Allocator::new` function as unsafe and documented the expected lifetime for the device and instance handles.

I will be closing this for now. If you have a better solution for this, feel free to open a PR.

**Comment by MarijnS95** [comment]
Struct definition order makes no difference because `ash::Device` intentionally doesn't implement `Drop` semantics. When calling `instance.destroy_device()` in `impl Drop for VulkanThing` you still have to _manually_ make sure `vk_mem::Allocator` is dropped beforehand via `ManuallyDrop<>`.

**Comment by MarijnS95** [comment]
@Neo-Zhixing you might want to look at how your docs render. Not having an empty newline makes the text render as one crammed-together paragraph.

Safety docs typically use a heading like `# Safety` anyway.

**Comment by Neo-Zhixing** [comment]
That's a good point. Thanks
